name: Alicia Sturdy Blog
favicon: null
layout_spectrum: 0.21107
title: The Journal of Alicia Sturdy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bfbbba'
    - '#2e2110'
    - '#8e8e8e'
    - '#bb4471'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: b5021ab0-e2d2-4c7e-9a26-1f15db52588d
    url: null
